# Site settings
name: Desqer
title: Developers - Desqer
email: dev@desqer.com
description: ""
baseurl: ""
url: "http://dev.desqer.com"
timezone: America/Sao_Paulo
locale: pt_BR
permalink: none

facebook_publisher:
facebook_author:

facebook_pixel_id:
google_analytics_id: UA-88846136-1\

# i18n
languages: ["en", "pt"]
default_lang: "pt"
exclude_from_localization: ["javascript", "images", "css", "assets"]
parallel_localization: true

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-polyglot
